# Requires credentials for a Wiz Service Account to authenticate to Wiz.
# Reference: https://docs.wiz.io/wiz-docs/docs/service-accounts-settings
#
# Wiz Service Account permissions: create:security_scans.
# Reference: https://docs.wiz.io/wiz-docs/docs/github-pipeline
#
# Store CLIENT_ID as secrets.WIZ_CLIENT_ID and SECRET as secrets.WIZ_CLIENT_SECRET
# Reference: https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions

name: 'wiz-iac-scan'

on:
  pull_request:
    branches:
    - main
    paths:
    - 'terraform/aws/example.tf'
  workflow_dispatch:

jobs:
  wiz-iac-scan:
    name: 'WizCLI IaC Scan'
    env:
      SCAN_PATH: 'terraform/aws/example.tf'
      CICD_IAC_POLICIES: 'SecCloudDev-Demo-Block-s3-Example,SecCloudDev-Demo-Block-Secrets'

    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download WizCLI
      run: |
        curl -o wizcli https://wizcli.app.wiz.io/latest/wizcli && chmod +x wizcli

    - name: Set Wiz Environment
      run: |
        echo "WIZ_ENV=demo" >> $GITHUB_ENV
      if: ${{ startsWith(github.event.pull_request.head.ref, 'wiz_demo_env') }}

    - name: Optionally Authenticate to Wiz Demo Tenant
      run: |
        env
        ./wizcli auth --id "${WIZ_CLIENT_ID}" --secret "${WIZ_CLIENT_SECRET}"
      env:
        WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID_DEMO }}
        WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET_DEMO }}
      if: ${{ startsWith(github.event.pull_request.head.ref, 'wiz_demo_env') }}

    - name: Otherwise Authenticate to Wiz Main Tenant
      run: |
        ./wizcli auth --id "${WIZ_CLIENT_ID}" --secret "${WIZ_CLIENT_SECRET}"
      env:
        WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
        WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
      if: ${{ !startsWith(github.event.pull_request.head.ref, 'wiz_demo_env') }}

    - name: Run WizCLI IaC Scan
      run: |
        ./wizcli iac scan --path "${SCAN_PATH}" --policy "${CICD_IAC_POLICIES}" --policy-hits-only --output wiz-iac-scan-results.json,sarif,true

    - uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: wiz-iac-scan-results.json
      if: ${{ github.event_name == 'pull_request' && ( success() || failure() ) }}
