# Requires credentials for a Wiz Service Account to authenticate to Wiz.
# Reference: https://docs.wiz.io/wiz-docs/docs/service-accounts-settings
#
# Wiz Service Account permissions: create:security_scans.
# Reference: https://docs.wiz.io/wiz-docs/docs/github-pipeline
#
# Store CLIENT_ID as secrets.WIZ_CLIENT_ID and SECRET as secrets.WIZ_CLIENT_SECRET
# Reference: https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions

name: 'wiz-iac-scan'

on:
  pull_request:
    branches:
    - main
    paths:
      - 'terraform/**'
  push:
    branches:
    - 'main'
    paths:
    - 'terraform/**'
  workflow_dispatch:

jobs:
  wiz-iac-scan-az:
    name: 'WizCLI IaC Scan'
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    environment: iman@wiz
    env:
      SCAN_PATH: 'terraform/azure'
      CICD_IAC_POLICIES: '"[Iman] Audit IaC policy","[Iman] Blocking IaC policy"'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download WizCLI
      run: |
        curl -sLo wizcli https://wizcli.app.wiz.io/latest/wizcli && chmod +x wizcli

    - name: Authenticate to Wiz
      run: |
        ./wizcli auth --id "${{ vars.WIZ_CLIENT_ID }}" --secret "${{ secrets.WIZ_CLIENT_SECRET }}"

    - name: Run WizCLI IaC Scan
      run: |
        ./wizcli iac scan --path "${SCAN_PATH}" --policy "${CICD_IAC_POLICIES}" --policy-hits-only --output wiz-iac-scan-results.json,sarif,true

    - uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: wiz-iac-scan-results.json
      if: ${{ github.event_name == 'pull_request' && ( success() || failure() ) }}
